SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk
include $(PATH_ROOT)/Config.kmk

LIBRARIES += libs16db

libs16db_TEMPLATE = CXX
libs16db_ORDERDEPS = $(PATH_ROOT)/hdr/repositoryd_rpc.h
libs16db_SOURCES = object.c translate.c


$(PATH_ROOT)/hdr/repositoryd_rpc.h: repositoryd/repositoryd.x
	@printf " RPCGEN(H) \t$(@)\n"
	@rpcgen -C -N -h $< > $@

include $(FILE_KBUILD_SUB_FOOTER)
