SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk
include $(PATH_ROOT)/Config.kmk

LIBRARIES += libs16db

libs16db_TEMPLATE = CXX
libs16db_SOURCES = object.c translate.c

include $(FILE_KBUILD_SUB_FOOTER)
