SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk
include $(PATH_ROOT)/Config.kmk

LIBRARIES += libs16db

libs16db_TEMPLATE = CXX
libs16db_SOURCES = translate.c rpc.c $(libreporpc_1_TARGET)
libs16db_DEPS += $(PATH_ROOT)/hdr/repositoryd_rpc.h 


include $(FILE_KBUILD_SUB_FOOTER)
