SUB_DEPTH = .
BUILD_TYPE ?= debug
include $(KBUILD_PATH)/subheader.kmk

include $(PATH_CURRENT)/external/Makefile.kmk

include $(PATH_CURRENT)/lib/Makefile.kmk

include $(PATH_CURRENT)/init/Makefile.kmk
include $(PATH_CURRENT)/repositoryd/Makefile.kmk
include $(PATH_CURRENT)/svccfg/Makefile.kmk
include $(PATH_CURRENT)/systemdr/Makefile.kmk

include $(FILE_KBUILD_SUB_FOOTER)
