SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk
include $(PATH_ROOT)/Config.kmk

LIBRARIES += libs16

libs16_TEMPLATE = CXX
libs16_ORDERDEPS = $(PATH_ROOT)/hdr/repositoryd_rpc.h
libs16_SOURCES = object.c
libs16_CLEAN += $(PATH_ROOT)/hdr/repositoryd_rpc.h

$(PATH_ROOT)/hdr/repositoryd_rpc.h: repositoryd/repositoryd.x
	@printf " RPCGEN(H) \t$(@)\n"
	@rpcgen -C -N -h $< > $@

include $(FILE_KBUILD_SUB_FOOTER)
