SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk
include $(PATH_ROOT)/Config.kmk

LIBRARIES += libs16

libs16_TEMPLATE = CXX
libs16_ORDERDEPS = $(PATH_ROOT)/hdr/repositoryd_rpc.h
libs16_SOURCES = object.c list.c

include $(FILE_KBUILD_SUB_FOOTER)
