SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk
include $(PATH_ROOT)/Config.kmk

PROGRAMS += s16.repositoryd

s16.repositoryd_TEMPLATE = CXX
s16.repositoryd_SOURCES = repositoryd.c

include $(FILE_KBUILD_SUB_FOOTER)
