SUB_DEPTH = ../..
include $(KBUILD_PATH)/subheader.kmk
include $(PATH_ROOT)/Config.kmk

PROGRAMS += s16.restartd

s16.restartd_TEMPLATE = CXX
s16.restartd_LIBS = $(libs16rr_1_TARGET) $(libs16db_1_TARGET) \
    $(libs16_1_TARGET) $(librestartsvc_1_TARGET) \
    $(librestartrpc_1_TARGET)
s16.restartd_SOURCES = restartd.c interface.c unit.c configd.c timer.c
s16.restartd_DEPS += $(PATH_ROOT)/hdr/restartd_rpc.h

include $(FILE_KBUILD_SUB_FOOTER)
